### ISSUE TITLE
Broken demo

### ISSUE THREAD

**Issue by njordhov** [Kah0ona/re-dnd#5]
Release 0.1.8 broke the demo, with the drag box not aligned with the mouse moves and failing to disappear on drop.

**Comment by njordhov** [comment]
Fixed in PR #4.

**Comment by veikman** [comment]
Even with that PR, the readme’s instruction for starting the demo (`lein dev`) appears to be incorrect (“'dev' is not a task”), and the amount of template crud left in the project is confusing to a newcomer like me.

For example, there’s both a demo.html and a figwheel.html, with the former referring to `js/compiled/app-demo.js` in place of `js/client.js`, while the live demo uses index.html.

**Comment by Kah0ona** [comment]
Hi Folks,

I somehow missed these communications, due to a wrong email filter. Thanks for the suggestion @veikman, I realize this needs a lot of tidying up, will try to do some of this now.

PR is merged. Docs will be updated now.
